version: '3.8'
services:
  postgres:
    hostname: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: buy4wheels
      POSTGRES_USER: root
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - "8085:8085"