version: '3.8'
services:
#  mysql:
#    hostname: mysql
#    image: mysql:5.7
#    environment:
#      MYSQL_ROOT_PASSWORD: rootpassword
#      MYSQL_DATABASE: buy4wheels
#      MYSQL_USER: root
#      MYSQL_PASSWORD: rootpassword
#    ports:
#      - "3306:3306"
#
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - "8085:8080"

  service1:
    build:
      context: ./Buy4Wheels-auth
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mysql

  service2:
    build:
      context: ./Buy4Wheels-car
      dockerfile: Dockerfile
    ports:
      - "8010:8010"
    depends_on:
      - mysql
    profiles:
      - docker

  service3:
    build:
      context: ./Buy4Wheels-offer
      dockerfile: Dockerfile
    ports:
      - "8030:8030"
    depends_on:
      - mysql
    profiles:
      - docker
