db:
  name: buy4wheels
  username: "root"
  password: "rootpassword"
  # Użyj nazwy serwisu MySQL z docker-compose.yml jako nazwy hosta zamiast localhost
  url: jdbc:mysql://mysql:3306/${db.name}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
  driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8030

spring:
  datasource:
    driver-class-name: ${db.driver-class-name}
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    static-path-pattern: /**

apis:
  # Użyj nazw serwisów z docker-compose.yml jako hostów
  buy4wheels-car:
    url: http://service2:8010
  buy4wheels-auth:
    url: http://service1:8000

feign:
  client:
    config:
      buy4wheels-car:
        # Ponownie, użyj nazwy serwisu jako hosta
        url: http://service2:8010
