db:
  name: buy4wheels
  username: "root"
  password: ""
  url: jdbc:mysql://localhost:3306/${db.name}
  driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8010
spring:
  datasource:
    driver-class-name: ${db.driver-class-name}
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    static-path-pattern: /**

apis:
  warehouseman-auth:
    url: http://localhost:8000