# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'oracle'
        cache: maven
        
    #service 1
    - name: Install Buy4Wheels-lib
      run: mvn -B install -DskipTests
      working-directory: ./Buy4Wheels-lib
        
    #service 2
    - name: Install Buy4Wheels-auth API module
      run: mvn -B install -DskipTests
      working-directory: ./Buy4Wheels-auth

    #service 3
    - name: Install Buy4Wheels-car API module
      run: mvn -B install
      working-directory: ./Buy4Wheels-car

    #service 4
    - name: Build Buy4Wheels-offer
      run: mvn -B install -DskipTests
      working-directory: ./Buy4Wheels-offer
